import { Project, Lead, ProjectType } from "./types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    raw_title: "Permohonan Dana Bumbung Bocor",
    raw_summary: "Masjid kami mengalami kebocoran serius di ruang solat wanita. Perlu baiki segera sebelum musim hujan.",
    extracted_mosque_name: "Masjid Al-Falah",
    state: "Selangor",
    source_type: "Manual Submission",
    lead_score: 85,
    status: "Pending",
    detected_project_type: "Renovation",
    detected_bank_name: "Maybank",
    detected_acc_number: "1234567890",
    detected_acc_name: "Masjid Al-Falah",
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString()
  },
  {
    id: "lead-2",
    raw_title: "Projek Pembinaan Pagar Masjid",
    raw_summary: "Kami ingin membina pagar baru untuk keselamatan kawasan masjid dan tanah perkuburan bersebelahan.",
    extracted_mosque_name: "Masjid Nurul Huda",
    state: "Johor",
    source_type: "Manual Submission",
    lead_score: 45,
    status: "Needs Manual Check",
    detected_project_type: "Construction",
    detected_bank_name: "CIMB",
    detected_acc_number: "0987654321",
    detected_acc_name: "Tabung Pembangunan Masjid",
    created_at: new Date(Date.now() - 172800000).toISOString(),
    updated_at: new Date(Date.now() - 172800000).toISOString()
  }
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    slug: "masjid-lestari-putra-construction",
    mosque_name: "Masjid Lestari Putra",
    state: "Selangor",
    district: "Seri Kembangan",
    title: "Tapak Pembangunan Masjid Lestari Putra",
    short_description: "Pembangunan tapak masjid baru untuk komuniti Lestari Putra.",
    full_description: "Pembangunan tapak masjid baru untuk komuniti Lestari Putra yang sedang berkembang pesat. Mari bersama berwakaf untuk rumah Allah.",
    project_type: "Construction",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 500000,
    collected_amount: 150000,
    completion_percent: 30,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "/images/qr-cropped.png",
    bank_name: "Maybank",
    account_name: "MASJID LESTARI PUTRA",
    account_number: "562807545820",
    image_url: "/images/masjid-lestari-putra.png",
    contact_person: "Haji Rozali Bin Lebai Awang",
    contact_phone: "60108443594",
    address: "Persiaran Lestari Putra 3, Taman Lestari Putra, Bandar Putra Permai, 43300 Seri Kembangan, Selangor.",
    google_maps_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1500!2d101.666111!3d3.010111!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cdb5a034638a29%3A0xe5a363a0a3a60!2sMasjid%20Lestari%20Putra!5e0!3m2!1sen!2smy!4v1710332000000!5m2!1sen!2smy",
    source_url: "https://www.facebook.com/masjidalhasanahbbb"
  },
  {
    id: "p2",
    slug: "masjid-al-hidayah-shah-alam-pembinaan",
    mosque_name: "Masjid Al-Hidayah",
    state: "Selangor",
    district: "Shah Alam",
    title: "Dana Pembinaan Menara & Kubah Utama",
    short_description: "Bantu kami menyiapkan struktur menara dan kubah masjid yang kini terbengkalai 60%.",
    full_description: "Masjid Al-Hidayah merupakan pusat komuniti penting di Seksyen 7. Kami kini memerlukan dana tambahan untuk menyiapkan pembinaan menara setinggi 30 meter dan kubah utama agar masjid dapat digunakan sepenuhnya menjelang Ramadhan depan.",
    project_type: "Construction",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 500000,
    collected_amount: 325000,
    completion_percent: 65,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidAlHidayah_QR",
    bank_name: "Maybank",
    account_name: "Bendahari Masjid Al-Hidayah",
    account_number: "562106712345",
    image_url: "https://images.unsplash.com/photo-1542667593-37ad9224edd0?auto=format&fit=crop&q=80&w=800",
    contact_person: "Haji Ahmad Bin Mansur",
    contact_phone: "60123456789",
    address: "Persiaran Masjid, Seksyen 7, 40000 Shah Alam, Selangor",
    google_maps_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d15936.438415785002!2d101.488667!3d3.073333!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc52e18585ea15%3A0xc6a80436d6a2f44!2sMasjid%20Al-Hidayah!5e0!3m2!1sen!2smy!4v1710321234567!5m2!1sen!2smy"
  },
  {
    id: "p3",
    slug: "surau-at-taqwa-ipoh-renovasi",
    mosque_name: "Surau At-Taqwa",
    state: "Perak",
    district: "Ipoh",
    title: "Projek Baik Pulih Sistem Penghawa Dingin",
    short_description: "Membaik pulih sistem penyejukan untuk keselesaan jemaah waktu solat Jumaat.",
    full_description: "Sistem penghawa dingin sedia ada telah berusia 15 tahun dan kerap rosak. Kami ingin menggantikannya dengan sistem yang lebih cekap tenaga untuk mengurangkan kos penyelenggaraan jangka panjang.",
    project_type: "Renovation",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 80000,
    collected_amount: 12000,
    completion_percent: 15,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=SurauAtTaqwa_QR",
    bank_name: "CIMB Bank",
    account_name: "Jawatankuasa Surau At-Taqwa",
    account_number: "8604561234",
    image_url: "https://images.unsplash.com/photo-1591147139223-8367561333ec?auto=format&fit=crop&q=80&w=800",
    contact_person: "Ustaz Hamdan",
    contact_phone: "601122334455",
    address: "Jalan Taqwa, Kampung Melayu, 30000 Ipoh, Perak",
    google_maps_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3976.920245648873!2d101.075!3d4.59!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2sSurau%20At-Taqwa!5e0!3m2!1sen!2smy!4v1710321234568!5m2!1sen!2smy"
  },
  {
    id: "p4",
    slug: "masjid-jamek-kuala-lumpur-maintenance",
    mosque_name: "Masjid Jamek Sultan Abdul Samad",
    state: "Kuala Lumpur",
    district: "City Centre",
    title: "Penyelenggaraan Karpet & Sistem Bunyi",
    short_description: "Penukaran karpet ruang solat utama dan naik taraf sistem pembesar suara.",
    full_description: "Sebagai salah satu masjid tertua di KL, penyelenggaraan berkala amat kritikal. Kami memohon sumbangan orang ramai untuk menukar karpet yang telah usang dan meningkatkan kualiti sistem bunyi.",
    project_type: "Maintenance",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 150000,
    collected_amount: 85000,
    completion_percent: 56,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidJamek_QR",
    bank_name: "Bank Islam",
    account_name: "Lembaga Pentadbir Masjid Jamek",
    account_number: "14014010123456",
    image_url: "https://images.unsplash.com/photo-1542667593-37ad9224edd0?auto=format&fit=crop&q=80&w=800",
    contact_person: "Imam Khalil",
    contact_phone: "60177788990",
    address: "Jalan Tun Perak, City Centre, 50050 Kuala Lumpur",
    google_maps_url: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3983.824245648873!2d101.696!3d3.149!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31cc482705096a6f%3A0x7d6c5d18585ea15!2sMasjid%20Jamek%20Sultan%20Abdul%20Samad!5e0!3m2!1sen!2smy!4v1710321234569!5m2!1sen!2smy"
  },
  {
    id: "p5",
    slug: "masjid-an-nur-johor-bahru-emergency",
    mosque_name: "Masjid An-Nur",
    state: "Johor",
    district: "Johor Bahru",
    title: "Tabung Baik Pulih Kerosakan Banjir",
    short_description: "Bantuan segera untuk membaiki kerosakan elektrik akibat banjir besar.",
    full_description: "Banjir kilat baru-baru ini telah menyebabkan kerosakan teruk pada sistem elektrik dan perabot masjid. Kami memerlukan bantuan segera untuk baik pulih agar aktiviti keagamaan dapat diteruskan.",
    project_type: "Emergency Fund",
    verification_status: "Basic Checked",
    publish_status: "Published",
    target_amount: 100000,
    collected_amount: 5000,
    completion_percent: 5,
    needs_donation: true,
    donation_method_type: "DuitNow QR",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidAnNurEmergency",
    image_url: "https://images.unsplash.com/photo-1579613832107-4ba9f02e7ba7?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "p6",
    slug: "masjid-nurul-iman-penang-construction",
    mosque_name: "Masjid Nurul Iman",
    state: "Pulau Pinang",
    district: "Georgetown",
    title: "Pembinaan Pusat Tahfiz & Kelas Fardu Ain",
    short_description: "Membina bangunan 2 tingkat untuk kemudahan pendidikan anak-anak kariah.",
    full_description: "Kami ingin membina pusat pendidikan yang lebih kondusif. Dana diperlukan untuk fasa pertama (asas dan struktur bawah).",
    project_type: "Construction",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 300000,
    collected_amount: 120000,
    completion_percent: 40,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidNurulIman_QR",
    bank_name: "Public Bank",
    account_name: "Dana Pendidikan Nurul Iman",
    account_number: "3122445566",
    image_url: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&q=80&w=800"
  },
  {
    id: "p7",
    slug: "surau-al-ikhlas-kuching-maintenance",
    mosque_name: "Surau Al-Ikhlas",
    state: "Sarawak",
    district: "Kuching",
    title: "Naik Taraf Bumbung & Sistem Siling",
    short_description: "Menyelesaikan masalah kebocoran bumbung yang menjejaskan ruang solat.",
    full_description: "Surau kami mengalami masalah kebocoran serius setiap kali hujan lebat. Kami memerlukan sumbangan untuk menukar atap zink kepada atap yang lebih tahan lama.",
    project_type: "Maintenance",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 45000,
    collected_amount: 38000,
    completion_percent: 84,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=SurauAlIkhlas_QR",
    bank_name: "RHB Bank",
    account_name: "Jawatankuasa Pembinaan Al-Ikhlas",
    account_number: "26210600012345",
    image_url: "https://images.unsplash.com/photo-1584551236674-51f1c289984f?auto=format&fit=crop&q=80&w=800"
  }
];
