import { Project } from "./types";

export const MOCK_PROJECTS: Project[] = [
  {
    slug: "masjid-al-hidayah-shah-alam-pembinaan",
    mosque_name: "Masjid Al-Hidayah",
    state: "Selangor",
    district: "Shah Alam",
    title: "Dana Pembinaan Menara & Kubah Utama",
    short_description: "Bantu kami menyiapkan struktur menara dan kubah masjid yang kini terbengkalai 60%.",
    full_description: "Masjid Al-Hidayah merupakan pusat komuniti penting di Seksyen 7. Kami kini memerlukan dana tambahan untuk menyiapkan pembinaan menara setinggi 30 meter dan kubah utama agar masjid dapat digunakan sepenuhnya menjelang Ramadhan depan.",
    project_type: "Construction",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 500000,
    collected_amount: 325000,
    completion_percent: 65,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidAlHidayah_QR",
    bank_name: "Maybank",
    account_name: "Bendahari Masjid Al-Hidayah",
    account_number: "562106712345",
    image_url: "https://images.unsplash.com/photo-1542623024-a797a7a48d60?auto=format&fit=crop&q=80&w=800"
  },
  {
    slug: "surau-at-taqwa-ipoh-renovasi",
    mosque_name: "Surau At-Taqwa",
    state: "Perak",
    district: "Ipoh",
    title: "Projek Baik Pulih Sistem Penghawa Dingin",
    short_description: "Membaik pulih sistem penyejukan untuk keselesaan jemaah waktu solat Jumaat.",
    full_description: "Sistem penghawa dingin sedia ada telah berusia 15 tahun dan kerap rosak. Kami ingin menggantikannya dengan sistem yang lebih cekap tenaga untuk mengurangkan kos penyelenggaraan jangka panjang.",
    project_type: "Renovation",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 80000,
    collected_amount: 12000,
    completion_percent: 15,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=SurauAtTaqwa_QR",
    bank_name: "CIMB Bank",
    account_name: "Jawatankuasa Surau At-Taqwa",
    account_number: "8604561234",
    image_url: "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?auto=format&fit=crop&q=80&w=800"
  },
  {
    slug: "masjid-jamek-kuala-lumpur-maintenance",
    mosque_name: "Masjid Jamek Sultan Abdul Samad",
    state: "Kuala Lumpur",
    district: "City Centre",
    title: "Penyelenggaraan Karpet & Sistem Bunyi",
    short_description: "Penukaran karpet ruang solat utama dan naik taraf sistem pembesar suara.",
    full_description: "Sebagai salah satu masjid tertua di KL, penyelenggaraan berkala amat kritikal. Kami memohon sumbangan orang ramai untuk menukar karpet yang telah usang dan meningkatkan kualiti sistem bunyi.",
    project_type: "Maintenance",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 150000,
    collected_amount: 85000,
    completion_percent: 56,
    needs_donation: true,
    donation_method_type: "Bank Transfer",
    bank_name: "Bank Islam",
    account_name: "Lembaga Pentadbir Masjid Jamek",
    account_number: "14014010123456",
    image_url: "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?auto=format&fit=crop&q=80&w=800"
  },
  {
    slug: "masjid-an-nur-johor-bahru-emergency",
    mosque_name: "Masjid An-Nur",
    state: "Johor",
    district: "Johor Bahru",
    title: "Tabung Baik Pulih Kerosakan Banjir",
    short_description: "Bantuan segera untuk membaiki kerosakan elektrik akibat banjir besar.",
    full_description: "Banjir kilat baru-baru ini telah menyebabkan kerosakan teruk pada sistem elektrik dan perabot masjid. Kami memerlukan bantuan segera untuk baik pulih agar aktiviti keagamaan dapat diteruskan.",
    project_type: "Emergency Fund",
    verification_status: "Basic Checked",
    publish_status: "Published",
    target_amount: 100000,
    collected_amount: 5000,
    completion_percent: 5,
    needs_donation: true,
    donation_method_type: "DuitNow QR",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidAnNurEmergency",
    image_url: "https://images.unsplash.com/photo-1596489807341-334148ef20ff?auto=format&fit=crop&q=80&w=800"
  },
  {
    slug: "masjid-nurul-iman-penang-construction",
    mosque_name: "Masjid Nurul Iman",
    state: "Pulau Pinang",
    district: "Georgetown",
    title: "Pembinaan Pusat Tahfiz & Kelas Fardu Ain",
    short_description: "Membina bangunan 2 tingkat untuk kemudahan pendidikan anak-anak kariah.",
    full_description: "Kami ingin membina pusat pendidikan yang lebih kondusif. Dana diperlukan untuk fasa pertama (asas dan struktur bawah).",
    project_type: "Construction",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 300000,
    collected_amount: 120000,
    completion_percent: 40,
    needs_donation: true,
    donation_method_type: "Both",
    duitnow_qr_url: "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=MasjidNurulIman_QR",
    bank_name: "Public Bank",
    account_name: "Dana Pendidikan Nurul Iman",
    account_number: "3122445566",
    image_url: "https://images.unsplash.com/photo-1584551271241-7d32cb33c415?auto=format&fit=crop&q=80&w=800"
  },
  {
    slug: "surau-al-ikhlas-kuching-maintenance",
    mosque_name: "Surau Al-Ikhlas",
    state: "Sarawak",
    district: "Kuching",
    title: "Naik Taraf Bumbung & Sistem Siling",
    short_description: "Menyelesaikan masalah kebocoran bumbung yang menjejaskan ruang solat.",
    full_description: "Surau kami mengalami masalah kebocoran serius setiap kali hujan lebat. Kami memerlukan sumbangan untuk menukar atap zink kepada atap yang lebih tahan lama.",
    project_type: "Maintenance",
    verification_status: "Verified",
    publish_status: "Published",
    target_amount: 45000,
    collected_amount: 38000,
    completion_percent: 84,
    needs_donation: true,
    donation_method_type: "Bank Transfer",
    bank_name: "RHB Bank",
    account_name: "Jawatankuasa Pembinaan Al-Ikhlas",
    account_number: "26210600012345",
    image_url: "https://images.unsplash.com/photo-1621506289937-23423f790c37?auto=format&fit=crop&q=80&w=800"
  }
];
